### ISSUE TITLE
[Question] How to precise a match group

### ISSUE THREAD

**Issue by Geobert** [duc12597/insomnia-plugin-response-regex#3]
Hi, 

I've asked this on the other issue but I think it would be more appropriate to open a new question for this.

I have this value `http://127.0.0.1:19444/callback?code=EtGFCZTxr6rymfsIg0DRPQ%3D%3D&state=random`

and I want to extract the `code` value.

I'm rolling with this regex: `code=(.*)&`

but the preview is giving: `code=EtGFCZTxr6rymfsIg0DRPQ%3D%3D&,EtGFCZTxr6rymfsIg0DRPQ%3D%3D`

How do I keep only the second one?

**Comment by duc12597** [comment]
Just to clarify, do you want the preview to show `code=EtGFCZTxr6rymfsIg0DRPQ%3D%3D&` or `EtGFCZTxr6rymfsIg0DRPQ%3D%3D`?

**Comment by Geobert** [comment]
Thanks for your answer! I only want `code`'s value, so `EtGFCZTxr6rymfsIg0DRPQ%3D%3D`

and as a bonus question, is there a way to url decode the value as well?

**Comment by duc12597** [comment]
Then you can try this regex: `\w+%+\w+%+\w+`.
There is no way to URL decode atm

**Comment by Geobert** [comment]
I don't understand the regex, but the preview is now correct. I can't use it though because I need it decoded, but I'm closing as the regex is solved :) 

Thanks!
